[proxies]
"PuddinCat/BestClash" = "https://raw.githubusercontent.com/PuddinCat/BestClash/refs/heads/main/proxies.yaml"
"vxiaov/free_proxies" = "https://cdn.jsdelivr.net/gh/vxiaov/free_proxies@main/clash/clash.provider.yaml"
"freenode/openrunner" = "https://freenode.openrunner.net/uploads/20240807-clash.yaml"
"Misaka-blog/chromego_merge" = "https://raw.githubusercontent.com/Misaka-blog/chromego_merge/main/sub/merged_proxies_new.yaml"
"MrMohebi/xray-proxy-grabber-telegram" = "https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/clash-meta/all.yaml"
"NiceVPN123/NiceVPN" = "https://raw.githubusercontent.com/NiceVPN123/NiceVPN/main/Clash.yaml"
"aiboboxx/clashfree" = "https://raw.githubusercontent.com/aiboboxx/clashfree/main/clash.yml"
"anaer/Sub" = "https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml"
"chengaopan/AutoMergePublicNodes" = "https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml"
"ermaozi/get_subscribe" = "https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml"
"ermaozi01/free_clash_vpn" = "https://raw.githubusercontent.com/ermaozi01/free_clash_vpn/main/subscribe/clash.yml"
"lagzian/SS-Collector" = "https://raw.githubusercontent.com/lagzian/SS-Collector/main/mix_clash.yaml"
"mahdibland/ShadowsocksAggregator" = "https://raw.githubusercontent.com/mahdibland/ShadowsocksAggregator/master/Eternity.yml"
"mfuu/v2ray" = "https://raw.githubusercontent.com/mfuu/v2ray/master/clash.yaml"
"peasoft/NoMoreWalls" = "https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.yml"
"ronghuaxueleng/get_v2" = "https://raw.githubusercontent.com/ronghuaxueleng/get_v2/main/pub/combine.yaml"
"ts-sf/fly" = "https://raw.githubusercontent.com/ts-sf/fly/main/clash"
"yaney01/Yaney01" = "https://raw.githubusercontent.com/yaney01/Yaney01/main/temporary"
"yebekhe/TelegramV2rayCollector" = "https://raw.githubusercontent.com/yebekhe/TelegramV2rayCollector/main/sub/base64/mix"
"zhangkaiitugithub/passcro" = "https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml"
"tt.vg/freeclash" = "https://tt.vg/freeclash"