name: FreeNodes ClashFree Cleaner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
  push:
    paths:
      - '.github/workflows/freenodes-clashfree-cleaner.yml'
      - 'freenodes-clashfree-ss-cleaner-sys.py'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v4

      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 执行任务
        run: python ./freenodes-clashfree-ss-cleaner-sys.py

      - name: 提交更改
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add .
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S')"

      - name: 推送更改
        uses: ad-m/github-push-action@main
        with:
          branch: main