name: FreeNodes ClashFree Cleaner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - test
    paths:
      - '.github/workflows/freenodes-clashfree-cleaner.yml'
      - 'freenodes-clashfree-ss-cleaner-sys.py'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@v4
        with:
          ref: test

      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 执行任务
        run: python ./freenodes-clashfree-ss-cleaner-sys.py

      - name: 提交更改
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Auto-update: $(date '+%Y-%m-%d %H:%M:%S')"
            git push origin test
          else
            echo "没有文件更改，跳过提交和推送。"
          fi